version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres_db'
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=database'
    ports:
      - '5432'